PREFIX ?= cgwalters

f28:
	./build.sh registry.fedoraproject.org/fedora:28 $(PREFIX)/fedora-dev 28

rawhide:
	./build.sh registry.fedoraproject.org/fedora:rawhide $(PREFIX)/fedora-dev rawhide

c7:
	./build.sh registry.centos.org/centos/centos:7 $(PREFIX)/centos-dev 7

r7:
	./build.sh registry.access.redhat.com/rhel7 $(PREFIX)/rhel-dev 7

r8:
	./build.sh docker-registry.engineering.redhat.com/rhel-appstream/rhel8 $(PREFIX)/rhel-dev 8
